sudo: required
language: bash
services:
  - docker
jobs:
  include:
    - stage: test
      script:
        - docker-compose run --rm spark-submit /app/tests/run.py
      after_script:
        - docker-compose down -v
