version: '3'

services:
  spark-master:
    ports:
      - 4040:8080
    volumes:
      - .:/app

  spark-worker:
    volumes:
      - .:/app

  spark-submit:
    build: docker/submit
    depends_on:
      - spark-master
      - spark-worker
    environment:
      MASTER_HOST: spark-master
    volumes:
      - .:/app
