version: '3'

services:
  spark-master:
    build: master
    volumes:
      - ./data:/app/data

  spark-worker-1:
    build: worker
    depends_on:
      - spark-master

  spark-worker-2:
    build: worker
    depends_on:
      - spark-master
