version: '3'

services:
  spark-master:
    build: docker/master

  spark-worker:
    build: docker/worker
    command: spark://spark-master:7077
    depends_on:
      - spark-master

  spark-submit:
    build: docker/submit
    depends_on:
      - spark-master
    environment:
      MASTER_HOST: spark-master
