version: '3'

services:
  spark-master:
    build: docker/master

  spark-worker-1:
    build: docker/worker
    depends_on:
      - spark-master

  spark-worker-2:
    build: docker/worker
    depends_on:
      - spark-master
